name: Exploit

on:
  - push
  - pull_request

jobs:
  exploit:
    name: Exploit
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      DOCKER_IP:
      DOCKER_PORT:

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd exploit && pip install -r requirements.txt

    - name: Root tar for cache
      run: |
        sudo chown root /usr/bin/tar && sudo chmod u+s /usr/bin/tar

    - name: Cache apt packages
      id: cache-apt
      uses: actions/cache@v4
      env:
        cache-name: cache-apt
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ env.cache-name }}-${{ hashFiles('.github/install-docker.sh') }}
        restore-keys: |
          ${{ runner.os }}-apt-${{ env.cache-name }}-
          ${{ runner.os }}-apt-
          ${{ runner.os }}-

    - name: Install docker
      if: ${{ steps.cache-apt.outputs.cache-hit != 'true' }}
      run: bash .github/install-docker.sh

    - name: Build docker image
      run: |
        docker compose build

    - name: Up docker container
      run: |
        docker compose up -d
        DOCKER_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q))
        echo "Container IP: $DOCKER_IP"
        echo "DOCKER_IP=$DOCKER_IP" >> $GITHUB_ENV
        DOCKER_PORT=$(grep -oP 'EXPOSE \K[0-9]+' Dockerfile | tail -n1)
        [ -z "$DOCKER_PORT" ] && DOCKER_PORT=80
        echo "Container Port: $DOCKER_PORT"
        echo "DOCKER_PORT=$DOCKER_PORT" >> $GITHUB_ENV

    - name: Exploit
      run: |
        python exploit/exp.py '${{ env.DOCKER_IP }}:${{ env.DOCKER_PORT }}'

